@Library('sharedlibraries')_
pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload')
        {
            steps
            {
                script
                {
                    cicd.newgit("https://github.com/supriyalad/maven.git")
                }
            }
        }
        stage('ContinuousBuild')
        {
            steps
            {
                script
                {
                    cicd.maven()
                }
            }
        }
        stage('ContinuousDeployment')
        {
            steps
            {
                script
                {
                    cicd.deploy("172.31.91.148","testapp3")
                }
            }
        }
        stage('ContinuousTesting')
        {
            steps
            {
                script
                {
                    cicd.newgit("https://github.com/intelliqittrainings/FunctionalTesting.git")
                    cicd.test("/home/ubuntu/.jenkins/workspace/pipelinewithlibraries")
                }
            }
        }
        stage('ContinuousDelivery')
        {
            steps
            {
                script
                {
                    cicd.approval("manager")
                    cicd.deploy("172.31.87.233","prodapp3")
                }
            }
        }
    }
}
